# Warner Bros Data Cleaning from Scrapy Scrape

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./warner_bros.csv')

In [3]:
df

,year released,movie name,worldwide box,domestic box,international box
0,"2011,2018,2012,2019,2012,2008,2001,2013,2010,2...","Harry Potter and the Deathly Hallows: Part II,...","$1,328,766,590,$1,143,758,700,$1,082,228,107,$...","$381,193,157,$335,061,807,$448,139,099,$335,45...","$947,573,433,$808,696,893,$634,089,008,$737,05..."

# Cleaning up the data

In [4]:
df['year released']

0    2011,2018,2012,2019,2012,2008,2001,2013,2010,2...
Name: year released, dtype: object

In [5]:
years_expanded = df['year released'].str.split(',', expand=True)

RESHAPE DATA FOR MERGE!

In [6]:
a = years_expanded.T
a

       0
0   2011
1   2018
2   2012
3   2019
4   2012
..   ...
95  1999
96  2006
97  1998
98  2002
99  2008

[100 rows x 1 columns]

In [7]:
movie_name_expanded = df['movie name'].str.split(',',expand=True)

In [8]:
b = movie_name_expanded.T
b

                                                0
0   Harry Potter and the Deathly Hallows: Part II
1                                         Aquaman
2                           The Dark Knight Rises
3                                           Joker
4               The Hobbit: An Unexpected Journey
..                                            ...
95                                 The Green Mile
96                                   The Departed
97                                Lethal Weapon 4
98                                     Scooby-Doo
99                                    Gran Torino

[100 rows x 1 columns]

In [9]:
world_wide = df['worldwide box'].str.split("$", expand=True)

In [10]:
world_wide
c=world_wide.T
c.drop(0,inplace=True)

In [11]:
c.reset_index(inplace=True)
c

    index               0
0       1  1,328,766,590,
1       2  1,143,758,700,
2       3  1,082,228,107,
3       4  1,072,507,517,
4       5  1,014,938,545,
..    ...             ...
95     96    290,701,374,
96     97    289,660,619,
97     98    285,400,000,
98     99    276,294,164,
99    100     274,543,085

[100 rows x 2 columns]

In [12]:
domestic = df['domestic box'].str.split("$", expand=True)

In [13]:
d = domestic.T

In [14]:

d.drop(0,inplace=True)

In [15]:
d.reset_index(inplace=True)

In [16]:
d

    index             0
0       1  381,193,157,
1       2  335,061,807,
2       3  448,139,099,
3       4  335,451,311,
4       5  303,003,568,
..    ...           ...
95     96  136,801,374,
96     97  132,384,315,
97     98  130,444,603,
98     99  153,294,164,
99    100   148,095,302

[100 rows x 2 columns]

In [17]:
international = df['international box'].str.split("$", expand=True)

In [18]:
e=international.T

In [19]:
e.drop(0,inplace=True)

In [20]:
e.reset_index(inplace=True)

In [21]:
e

    index             0
0       1  947,573,433,
1       2  808,696,893,
2       3  634,089,008,
3       4  737,056,206,
4       5  711,934,977,
..    ...           ...
95     96  153,900,000,
96     97  157,276,304,
97     98  154,955,397,
98     99  123,000,000,
99    100   126,447,783

[100 rows x 2 columns]

# Time to merge!

Doesn't hurt to test it out!

In [22]:
test = pd.concat([a,b], axis=1)

In [23]:
test

       0                                              0
0   2011  Harry Potter and the Deathly Hallows: Part II
1   2018                                        Aquaman
2   2012                          The Dark Knight Rises
3   2019                                          Joker
4   2012              The Hobbit: An Unexpected Journey
..   ...                                            ...
95  1999                                 The Green Mile
96  2006                                   The Departed
97  1998                                Lethal Weapon 4
98  2002                                     Scooby-Doo
99  2008                                    Gran Torino

[100 rows x 2 columns]

In [24]:
test2 = pd.concat([a,b,c,d,e], axis=1)

In [25]:
test2

,0,0,index,0,index,0,index,0
0,2011,Harry Potter and the Deathly Hallows: Part II,1,"1,328,766,590,",1,"381,193,157,",1,"947,573,433,"
1,2018,Aquaman,2,"1,143,758,700,",2,"335,061,807,",2,"808,696,893,"
2,2012,The Dark Knight Rises,3,"1,082,228,107,",3,"448,139,099,",3,"634,089,008,"
3,2019,Joker,4,"1,072,507,517,",4,"335,451,311,",4,"737,056,206,"
4,2012,The Hobbit: An Unexpected Journey,5,"1,014,938,545,",5,"303,003,568,",5,"711,934,977,"
...,...,...,...,...,...,...,...,...
95,1999,The Green Mile,96,"290,701,374,",96,"136,801,374,",96,"153,900,000,"
96,2006,The Departed,97,"289,660,619,",97,"132,384,315,",97,"157,276,304,"
97,1998,Lethal Weapon 4,98,"285,400,000,",98,"130,444,603,",98,"154,955,397,"
98,2002,Scooby-Doo,99,"276,294,164,",99,"153,294,164,",99,"123,000,000,"
99,2008,Gran Torino,100,"274,543,085",100,"148,095,302",100,"126,447,783"

In [26]:
pd. set_option('display.max_rows', None)

In [28]:
warner_bros_csv = test2

Success! Let's Clean this up.

In [29]:
warner_bros_csv

,0,0,index,0,index,0,index,0
0,2011,Harry Potter and the Deathly Hallows: Part II,1,"1,328,766,590,",1,"381,193,157,",1,"947,573,433,"
1,2018,Aquaman,2,"1,143,758,700,",2,"335,061,807,",2,"808,696,893,"
2,2012,The Dark Knight Rises,3,"1,082,228,107,",3,"448,139,099,",3,"634,089,008,"
3,2019,Joker,4,"1,072,507,517,",4,"335,451,311,",4,"737,056,206,"
4,2012,The Hobbit: An Unexpected Journey,5,"1,014,938,545,",5,"303,003,568,",5,"711,934,977,"
5,2008,The Dark Knight,6,"998,615,789,",6,"533,720,947,",6,"464,894,842,"
6,2001,Harry Potter and the Sorcererâ€™s Stone,7,"965,054,122,",7,"317,871,467,",7,"647,182,655,"
7,2013,The Hobbit: The Desolation of Smaug,8,"959,358,436,",8,"258,241,522,",8,"701,116,914,"
8,2010,Harry Potter and the Deathly Hallows: Part I,9,"952,601,389,",9,"296,131,568,",9,"656,469,821,"
9,2014,The Hobbit: The Battle of the Five Armies,10,"940,389,558,",10,"255,119,788,",10,"685,269,770,"
10,2007,Harry Potter and the Order of the Phoenix,11,"939,619,849,",11,"292,137,260,",11,"647,482,589,"
11,2009,Harry Potter and the Half-Blood Prince,12,"929,411,069,",12,"302,089,278,",12,"627,321,791,"
12,2005,Harry Potter and the Goblet of Fire,13,"886,746,240,",13,"290,201,752,",13,"596,544,488,"
13,2002,Harry Potter and the Chamber of Secrets,14,"875,262,553,",14,"262,233,381,",14,"613,029,172,"
14,2016,Batman v Superman: Dawn of Justice,15,"872,395,091,",15,"330,360,194,",15,"542,034,897,"
15,2017,Wonder Woman,16,"818,058,221,",16,"412,563,408,",16,"405,494,813,"
16,2016,Fantastic Beasts and Where to Find Them,17,"811,724,385,",17,"234,037,575,",17,"577,686,810,"
17,2004,Harry Potter and the Prisoner of Azkaban,18,"789,592,708,",18,"249,757,726,",18,"539,834,982,"
18,2022,The Batman,19,"768,159,998,",19,"369,345,583,",19,"398,814,415,"
19,2016,Suicide Squad,20,"745,744,980,",20,"325,100,054,",20,"420,644,926,"
20,2003,The Matrix Reloaded,21,"738,576,929,",21,"281,553,689,",21,"457,023,240,"
21,2010,Inception,22,"728,582,465,",22,"292,576,195,",22,"436,006,270,"
22,2017,It,23,"701,083,042,",23,"328,828,874,",23,"372,254,168,"
23,2013,Gravity,24,"688,214,291,",24,"274,092,705,",24,"414,121,586,"
24,2013,Man of Steel,25,"667,999,518,",25,"291,045,518,",25,"376,954,000,"
25,2017,Justice League,26,"655,945,209,",26,"229,024,295,",26,"426,920,914,"
26,2018,Fantastic Beasts: The Crimes of Grindelwald,27,"648,455,339,",27,"159,555,901,",27,"488,899,438,"
27,2011,The Hangover Part II,28,"586,764,305,",28,"254,464,305,",28,"332,300,000,"
28,2007,I am Legend,29,"585,532,684,",29,"256,393,010,",29,"329,139,674,"
29,2018,Ready Player One,30,"579,055,653,",30,"137,690,172,",30,"441,365,481,"
30,2017,Kong: Skull Island,31,"561,072,059,",31,"168,052,812,",31,"393,019,247,"
31,2014,American Sniper,32,"547,326,372,",32,"350,126,372,",32,"197,200,000,"
32,2018,Tang Ren Jie Tan An 2,33,"544,068,574,",33,"1,983,984,",33,"542,084,590,"
33,2011,Sherlock Holmes: A Game of Shadows,34,"535,663,443,",34,"186,848,418,",34,"348,815,025,"
34,2014,Godzilla,35,"529,076,069,",35,"200,676,069,",35,"328,400,000,"
35,2018,The Meg,36,"527,370,715,",36,"145,443,742,",36,"381,926,973,"
36,2017,Dunkirk,37,"518,058,826,",37,"190,068,280,",37,"327,990,546,"
37,2009,Sherlock Holmes,38,"498,438,212,",38,"209,028,679,",38,"289,409,533,"
38,1996,Twister,39,"495,700,000,",39,"241,688,385,",39,"254,011,615,"
39,2010,Clash of the Titans,40,"493,214,888,",40,"163,214,888,",40,"330,000,000,"
40,2004,Troy,41,"483,152,040,",41,"133,298,577,",41,"349,853,463,"
41,2005,Charlie and the Chocolate Factory,42,"475,825,484,",42,"206,459,076,",42,"269,366,408,"
42,2019,It: Chapter Two,43,"469,566,806,",43,"211,593,228,",43,"257,973,578,"
43,2014,The Lego Movie,44,"468,084,718,",44,"257,784,718,",44,"210,300,000,"
44,2021,Godzilla vs. Kong,45,"468,064,628,",45,"100,916,094,",45,"367,148,534,"
45,1999,The Matrix,46,"465,974,198,",46,"173,993,387,",46,"291,980,811,"
46,2009,The Hangover,47,"465,487,583,",47,"277,322,503,",47,"188,165,080,"
47,2003,The Last Samurai,48,"456,810,575,",48,"111,110,575,",48,"345,700,000,"
48,2015,San Andreas,49,"456,258,539,",49,"155,190,832,",49,"301,067,707,"
49,2007,300,50,"454,161,935,",50,"210,614,939,",50,"243,546,996,"
50,2001,Ocean's Eleven,51,"450,728,529,",51,"183,417,150,",51,"267,311,379,"
51,2003,Terminator 3: Rise of the Machines,52,"433,058,296,",52,"150,358,296,",52,"282,700,000,"
52,2018,A Star is Born,53,"431,870,523,",53,"215,288,866,",53,"216,581,657,"
53,2019,PokÃ©mon: Detective Pikachu,54,"431,344,168,",54,"144,105,346,",54,"287,238,822,"
54,1973,The Exorcist,55,"428,214,478,",55,"230,347,346,",55,"197,867,132,"
55,2018,Rampage,56,"427,947,217,",56,"101,028,233,",56,"326,918,984,"
56,2003,The Matrix Revolutions,57,"427,300,260,",57,"139,270,910,",57,"288,029,350,"
57,2008,Sex and the City,58,"415,247,258,",58,"152,647,258,",58,"262,600,000,"
58,1989,Batman,59,"411,348,924,",59,"251,188,924,",59,"160,160,000,"
59,2013,Pacific Rim,60,"411,002,906,",60,"101,802,906,",60,"309,200,000,"
60,1992,The Bodyguard,61,"410,945,720,",61,"121,945,720,",61,"289,000,000,"
61,2022,Fantastic Beasts: The Secrets of Dumbledore,62,"398,848,696,",62,"95,850,844,",62,"302,997,852,"
62,2021,Dune,63,"398,601,500,",63,"108,327,830,",63,"290,273,670,"
63,2006,Superman Returns,64,"391,081,192,",64,"200,120,000,",64,"190,961,192,"
64,1991,Robin Hood: Prince of Thieves,65,"390,500,000,",65,"165,493,908,",65,"225,006,092,"
65,2006,Happy Feet,66,"385,000,317,",66,"198,000,317,",66,"187,000,000,"
66,2019,Godzilla: King of the Monsters,67,"383,299,915,",67,"110,500,138,",67,"272,799,777,"
67,2015,Mad Max: Fury Road,68,"367,457,874,",68,"153,636,354,",68,"213,821,520,"
68,2014,Edge of Tomorrow,69,"367,028,980,",69,"100,206,256,",69,"266,822,724,"
69,2009,Terminator Salvation,70,"365,491,792,",70,"125,322,469,",70,"240,169,323,"
70,2019,Shazam!,71,"363,664,533,",71,"140,371,656,",71,"223,292,877,"
71,2018,The Nun,72,"363,391,647,",72,"117,450,119,",72,"245,941,528,"
72,2004,Ocean's Twelve,73,"362,989,076,",73,"125,531,634,",73,"237,457,442,"
73,2020,Tenet,74,"362,450,957,",74,"58,504,105,",74,"303,946,852,"
74,2013,The Hangover 3,75,"362,000,072,",75,"112,200,072,",75,"249,800,000,"
75,2005,Batman Begins,76,"358,858,124,",76,"205,343,774,",76,"153,514,350,"
76,1993,The Fugitive,77,"353,715,317,",77,"183,875,760,",77,"169,839,557,"
77,2013,The Great Gatsby,78,"353,640,419,",78,"144,840,419,",78,"208,800,000,"
78,2016,The Legend of Tarzan,79,"348,902,025,",79,"126,643,061,",79,"222,258,964,"
79,1995,Batman Forever,80,"336,529,144,",80,"184,031,112,",80,"152,498,032,"
80,2014,300: Rise of an Empire,81,"330,780,051,",81,"106,580,051,",81,"224,200,000,"
81,2000,The Perfect Storm,82,"328,711,434,",82,"182,618,434,",82,"146,093,000,"
82,1992,Lethal Weapon 3,83,"319,700,000,",83,"144,731,527,",83,"174,968,473,"
83,2012,Journey 2: The Mysterious Island,84,"318,146,162,",84,"103,860,290,",84,"214,285,872,"
84,2013,The Conjuring,85,"317,744,402,",85,"137,400,141,",85,"180,344,261,"
85,2004,The Polar Express,86,"312,719,437,",86,"188,578,855,",86,"124,140,582,"
86,2007,Ocean's Thirteen,87,"311,744,465,",87,"117,144,465,",87,"194,600,000,"
87,2017,The Lego Batman Movie,88,"310,570,560,",88,"175,750,384,",88,"134,820,176,"
88,2016,The Conjuring 2: The Enfield Poltergeist,89,"310,201,399,",89,"102,470,008,",89,"207,731,391,"
89,2009,The Blind Side,90,"305,705,794,",90,"255,959,475,",90,"49,746,319,"
90,2017,Annabelle: Creation,91,"305,384,865,",91,"102,092,201,",91,"203,292,664,"
91,2012,Wrath of the Titans,92,"305,270,083,",92,"83,670,083,",92,"221,600,000,"
92,1978,Superman,93,"300,200,000,",93,"134,218,018,",93,"165,981,982,"
93,2018,Oceanâ€™s 8,94,"297,718,711,",94,"140,218,711,",94,"157,500,000,"
94,2010,Sex and the City 2,95,"294,680,778,",95,"95,347,692,",95,"199,333,086,"
95,1999,The Green Mile,96,"290,701,374,",96,"136,801,374,",96,"153,900,000,"
96,2006,The Departed,97,"289,660,619,",97,"132,384,315,",97,"157,276,304,"
97,1998,Lethal Weapon 4,98,"285,400,000,",98,"130,444,603,",98,"154,955,397,"
98,2002,Scooby-Doo,99,"276,294,164,",99,"153,294,164,",99,"123,000,000,"
99,2008,Gran Torino,100,"274,543,085",100,"148,095,302",100,"126,447,783"

Remove unwanted index columns

In [30]:
del warner_bros_csv['index']

In [31]:
warner_bros_csv

,0,0,0,0,0
0,2011,Harry Potter and the Deathly Hallows: Part II,"1,328,766,590,","381,193,157,","947,573,433,"
1,2018,Aquaman,"1,143,758,700,","335,061,807,","808,696,893,"
2,2012,The Dark Knight Rises,"1,082,228,107,","448,139,099,","634,089,008,"
3,2019,Joker,"1,072,507,517,","335,451,311,","737,056,206,"
4,2012,The Hobbit: An Unexpected Journey,"1,014,938,545,","303,003,568,","711,934,977,"
5,2008,The Dark Knight,"998,615,789,","533,720,947,","464,894,842,"
6,2001,Harry Potter and the Sorcererâ€™s Stone,"965,054,122,","317,871,467,","647,182,655,"
7,2013,The Hobbit: The Desolation of Smaug,"959,358,436,","258,241,522,","701,116,914,"
8,2010,Harry Potter and the Deathly Hallows: Part I,"952,601,389,","296,131,568,","656,469,821,"
9,2014,The Hobbit: The Battle of the Five Armies,"940,389,558,","255,119,788,","685,269,770,"
10,2007,Harry Potter and the Order of the Phoenix,"939,619,849,","292,137,260,","647,482,589,"
11,2009,Harry Potter and the Half-Blood Prince,"929,411,069,","302,089,278,","627,321,791,"
12,2005,Harry Potter and the Goblet of Fire,"886,746,240,","290,201,752,","596,544,488,"
13,2002,Harry Potter and the Chamber of Secrets,"875,262,553,","262,233,381,","613,029,172,"
14,2016,Batman v Superman: Dawn of Justice,"872,395,091,","330,360,194,","542,034,897,"
15,2017,Wonder Woman,"818,058,221,","412,563,408,","405,494,813,"
16,2016,Fantastic Beasts and Where to Find Them,"811,724,385,","234,037,575,","577,686,810,"
17,2004,Harry Potter and the Prisoner of Azkaban,"789,592,708,","249,757,726,","539,834,982,"
18,2022,The Batman,"768,159,998,","369,345,583,","398,814,415,"
19,2016,Suicide Squad,"745,744,980,","325,100,054,","420,644,926,"
20,2003,The Matrix Reloaded,"738,576,929,","281,553,689,","457,023,240,"
21,2010,Inception,"728,582,465,","292,576,195,","436,006,270,"
22,2017,It,"701,083,042,","328,828,874,","372,254,168,"
23,2013,Gravity,"688,214,291,","274,092,705,","414,121,586,"
24,2013,Man of Steel,"667,999,518,","291,045,518,","376,954,000,"
25,2017,Justice League,"655,945,209,","229,024,295,","426,920,914,"
26,2018,Fantastic Beasts: The Crimes of Grindelwald,"648,455,339,","159,555,901,","488,899,438,"
27,2011,The Hangover Part II,"586,764,305,","254,464,305,","332,300,000,"
28,2007,I am Legend,"585,532,684,","256,393,010,","329,139,674,"
29,2018,Ready Player One,"579,055,653,","137,690,172,","441,365,481,"
30,2017,Kong: Skull Island,"561,072,059,","168,052,812,","393,019,247,"
31,2014,American Sniper,"547,326,372,","350,126,372,","197,200,000,"
32,2018,Tang Ren Jie Tan An 2,"544,068,574,","1,983,984,","542,084,590,"
33,2011,Sherlock Holmes: A Game of Shadows,"535,663,443,","186,848,418,","348,815,025,"
34,2014,Godzilla,"529,076,069,","200,676,069,","328,400,000,"
35,2018,The Meg,"527,370,715,","145,443,742,","381,926,973,"
36,2017,Dunkirk,"518,058,826,","190,068,280,","327,990,546,"
37,2009,Sherlock Holmes,"498,438,212,","209,028,679,","289,409,533,"
38,1996,Twister,"495,700,000,","241,688,385,","254,011,615,"
39,2010,Clash of the Titans,"493,214,888,","163,214,888,","330,000,000,"
40,2004,Troy,"483,152,040,","133,298,577,","349,853,463,"
41,2005,Charlie and the Chocolate Factory,"475,825,484,","206,459,076,","269,366,408,"
42,2019,It: Chapter Two,"469,566,806,","211,593,228,","257,973,578,"
43,2014,The Lego Movie,"468,084,718,","257,784,718,","210,300,000,"
44,2021,Godzilla vs. Kong,"468,064,628,","100,916,094,","367,148,534,"
45,1999,The Matrix,"465,974,198,","173,993,387,","291,980,811,"
46,2009,The Hangover,"465,487,583,","277,322,503,","188,165,080,"
47,2003,The Last Samurai,"456,810,575,","111,110,575,","345,700,000,"
48,2015,San Andreas,"456,258,539,","155,190,832,","301,067,707,"
49,2007,300,"454,161,935,","210,614,939,","243,546,996,"
50,2001,Ocean's Eleven,"450,728,529,","183,417,150,","267,311,379,"
51,2003,Terminator 3: Rise of the Machines,"433,058,296,","150,358,296,","282,700,000,"
52,2018,A Star is Born,"431,870,523,","215,288,866,","216,581,657,"
53,2019,PokÃ©mon: Detective Pikachu,"431,344,168,","144,105,346,","287,238,822,"
54,1973,The Exorcist,"428,214,478,","230,347,346,","197,867,132,"
55,2018,Rampage,"427,947,217,","101,028,233,","326,918,984,"
56,2003,The Matrix Revolutions,"427,300,260,","139,270,910,","288,029,350,"
57,2008,Sex and the City,"415,247,258,","152,647,258,","262,600,000,"
58,1989,Batman,"411,348,924,","251,188,924,","160,160,000,"
59,2013,Pacific Rim,"411,002,906,","101,802,906,","309,200,000,"
60,1992,The Bodyguard,"410,945,720,","121,945,720,","289,000,000,"
61,2022,Fantastic Beasts: The Secrets of Dumbledore,"398,848,696,","95,850,844,","302,997,852,"
62,2021,Dune,"398,601,500,","108,327,830,","290,273,670,"
63,2006,Superman Returns,"391,081,192,","200,120,000,","190,961,192,"
64,1991,Robin Hood: Prince of Thieves,"390,500,000,","165,493,908,","225,006,092,"
65,2006,Happy Feet,"385,000,317,","198,000,317,","187,000,000,"
66,2019,Godzilla: King of the Monsters,"383,299,915,","110,500,138,","272,799,777,"
67,2015,Mad Max: Fury Road,"367,457,874,","153,636,354,","213,821,520,"
68,2014,Edge of Tomorrow,"367,028,980,","100,206,256,","266,822,724,"
69,2009,Terminator Salvation,"365,491,792,","125,322,469,","240,169,323,"
70,2019,Shazam!,"363,664,533,","140,371,656,","223,292,877,"
71,2018,The Nun,"363,391,647,","117,450,119,","245,941,528,"
72,2004,Ocean's Twelve,"362,989,076,","125,531,634,","237,457,442,"
73,2020,Tenet,"362,450,957,","58,504,105,","303,946,852,"
74,2013,The Hangover 3,"362,000,072,","112,200,072,","249,800,000,"
75,2005,Batman Begins,"358,858,124,","205,343,774,","153,514,350,"
76,1993,The Fugitive,"353,715,317,","183,875,760,","169,839,557,"
77,2013,The Great Gatsby,"353,640,419,","144,840,419,","208,800,000,"
78,2016,The Legend of Tarzan,"348,902,025,","126,643,061,","222,258,964,"
79,1995,Batman Forever,"336,529,144,","184,031,112,","152,498,032,"
80,2014,300: Rise of an Empire,"330,780,051,","106,580,051,","224,200,000,"
81,2000,The Perfect Storm,"328,711,434,","182,618,434,","146,093,000,"
82,1992,Lethal Weapon 3,"319,700,000,","144,731,527,","174,968,473,"
83,2012,Journey 2: The Mysterious Island,"318,146,162,","103,860,290,","214,285,872,"
84,2013,The Conjuring,"317,744,402,","137,400,141,","180,344,261,"
85,2004,The Polar Express,"312,719,437,","188,578,855,","124,140,582,"
86,2007,Ocean's Thirteen,"311,744,465,","117,144,465,","194,600,000,"
87,2017,The Lego Batman Movie,"310,570,560,","175,750,384,","134,820,176,"
88,2016,The Conjuring 2: The Enfield Poltergeist,"310,201,399,","102,470,008,","207,731,391,"
89,2009,The Blind Side,"305,705,794,","255,959,475,","49,746,319,"
90,2017,Annabelle: Creation,"305,384,865,","102,092,201,","203,292,664,"
91,2012,Wrath of the Titans,"305,270,083,","83,670,083,","221,600,000,"
92,1978,Superman,"300,200,000,","134,218,018,","165,981,982,"
93,2018,Oceanâ€™s 8,"297,718,711,","140,218,711,","157,500,000,"
94,2010,Sex and the City 2,"294,680,778,","95,347,692,","199,333,086,"
95,1999,The Green Mile,"290,701,374,","136,801,374,","153,900,000,"
96,2006,The Departed,"289,660,619,","132,384,315,","157,276,304,"
97,1998,Lethal Weapon 4,"285,400,000,","130,444,603,","154,955,397,"
98,2002,Scooby-Doo,"276,294,164,","153,294,164,","123,000,000,"
99,2008,Gran Torino,"274,543,085","148,095,302","126,447,783"

RENAME OUR COLUMNS

In [32]:
warner_bros_csv.columns=['year','movie name','worldwide box office','domestic box office','international box office']

# AWESOMENESS

In [33]:
warner_bros_csv

,year,movie name,worldwide box office,domestic box office,international box office
0,2011,Harry Potter and the Deathly Hallows: Part II,"1,328,766,590,","381,193,157,","947,573,433,"
1,2018,Aquaman,"1,143,758,700,","335,061,807,","808,696,893,"
2,2012,The Dark Knight Rises,"1,082,228,107,","448,139,099,","634,089,008,"
3,2019,Joker,"1,072,507,517,","335,451,311,","737,056,206,"
4,2012,The Hobbit: An Unexpected Journey,"1,014,938,545,","303,003,568,","711,934,977,"
5,2008,The Dark Knight,"998,615,789,","533,720,947,","464,894,842,"
6,2001,Harry Potter and the Sorcererâ€™s Stone,"965,054,122,","317,871,467,","647,182,655,"
7,2013,The Hobbit: The Desolation of Smaug,"959,358,436,","258,241,522,","701,116,914,"
8,2010,Harry Potter and the Deathly Hallows: Part I,"952,601,389,","296,131,568,","656,469,821,"
9,2014,The Hobbit: The Battle of the Five Armies,"940,389,558,","255,119,788,","685,269,770,"
10,2007,Harry Potter and the Order of the Phoenix,"939,619,849,","292,137,260,","647,482,589,"
11,2009,Harry Potter and the Half-Blood Prince,"929,411,069,","302,089,278,","627,321,791,"
12,2005,Harry Potter and the Goblet of Fire,"886,746,240,","290,201,752,","596,544,488,"
13,2002,Harry Potter and the Chamber of Secrets,"875,262,553,","262,233,381,","613,029,172,"
14,2016,Batman v Superman: Dawn of Justice,"872,395,091,","330,360,194,","542,034,897,"
15,2017,Wonder Woman,"818,058,221,","412,563,408,","405,494,813,"
16,2016,Fantastic Beasts and Where to Find Them,"811,724,385,","234,037,575,","577,686,810,"
17,2004,Harry Potter and the Prisoner of Azkaban,"789,592,708,","249,757,726,","539,834,982,"
18,2022,The Batman,"768,159,998,","369,345,583,","398,814,415,"
19,2016,Suicide Squad,"745,744,980,","325,100,054,","420,644,926,"
20,2003,The Matrix Reloaded,"738,576,929,","281,553,689,","457,023,240,"
21,2010,Inception,"728,582,465,","292,576,195,","436,006,270,"
22,2017,It,"701,083,042,","328,828,874,","372,254,168,"
23,2013,Gravity,"688,214,291,","274,092,705,","414,121,586,"
24,2013,Man of Steel,"667,999,518,","291,045,518,","376,954,000,"
25,2017,Justice League,"655,945,209,","229,024,295,","426,920,914,"
26,2018,Fantastic Beasts: The Crimes of Grindelwald,"648,455,339,","159,555,901,","488,899,438,"
27,2011,The Hangover Part II,"586,764,305,","254,464,305,","332,300,000,"
28,2007,I am Legend,"585,532,684,","256,393,010,","329,139,674,"
29,2018,Ready Player One,"579,055,653,","137,690,172,","441,365,481,"
30,2017,Kong: Skull Island,"561,072,059,","168,052,812,","393,019,247,"
31,2014,American Sniper,"547,326,372,","350,126,372,","197,200,000,"
32,2018,Tang Ren Jie Tan An 2,"544,068,574,","1,983,984,","542,084,590,"
33,2011,Sherlock Holmes: A Game of Shadows,"535,663,443,","186,848,418,","348,815,025,"
34,2014,Godzilla,"529,076,069,","200,676,069,","328,400,000,"
35,2018,The Meg,"527,370,715,","145,443,742,","381,926,973,"
36,2017,Dunkirk,"518,058,826,","190,068,280,","327,990,546,"
37,2009,Sherlock Holmes,"498,438,212,","209,028,679,","289,409,533,"
38,1996,Twister,"495,700,000,","241,688,385,","254,011,615,"
39,2010,Clash of the Titans,"493,214,888,","163,214,888,","330,000,000,"
40,2004,Troy,"483,152,040,","133,298,577,","349,853,463,"
41,2005,Charlie and the Chocolate Factory,"475,825,484,","206,459,076,","269,366,408,"
42,2019,It: Chapter Two,"469,566,806,","211,593,228,","257,973,578,"
43,2014,The Lego Movie,"468,084,718,","257,784,718,","210,300,000,"
44,2021,Godzilla vs. Kong,"468,064,628,","100,916,094,","367,148,534,"
45,1999,The Matrix,"465,974,198,","173,993,387,","291,980,811,"
46,2009,The Hangover,"465,487,583,","277,322,503,","188,165,080,"
47,2003,The Last Samurai,"456,810,575,","111,110,575,","345,700,000,"
48,2015,San Andreas,"456,258,539,","155,190,832,","301,067,707,"
49,2007,300,"454,161,935,","210,614,939,","243,546,996,"
50,2001,Ocean's Eleven,"450,728,529,","183,417,150,","267,311,379,"
51,2003,Terminator 3: Rise of the Machines,"433,058,296,","150,358,296,","282,700,000,"
52,2018,A Star is Born,"431,870,523,","215,288,866,","216,581,657,"
53,2019,PokÃ©mon: Detective Pikachu,"431,344,168,","144,105,346,","287,238,822,"
54,1973,The Exorcist,"428,214,478,","230,347,346,","197,867,132,"
55,2018,Rampage,"427,947,217,","101,028,233,","326,918,984,"
56,2003,The Matrix Revolutions,"427,300,260,","139,270,910,","288,029,350,"
57,2008,Sex and the City,"415,247,258,","152,647,258,","262,600,000,"
58,1989,Batman,"411,348,924,","251,188,924,","160,160,000,"
59,2013,Pacific Rim,"411,002,906,","101,802,906,","309,200,000,"
60,1992,The Bodyguard,"410,945,720,","121,945,720,","289,000,000,"
61,2022,Fantastic Beasts: The Secrets of Dumbledore,"398,848,696,","95,850,844,","302,997,852,"
62,2021,Dune,"398,601,500,","108,327,830,","290,273,670,"
63,2006,Superman Returns,"391,081,192,","200,120,000,","190,961,192,"
64,1991,Robin Hood: Prince of Thieves,"390,500,000,","165,493,908,","225,006,092,"
65,2006,Happy Feet,"385,000,317,","198,000,317,","187,000,000,"
66,2019,Godzilla: King of the Monsters,"383,299,915,","110,500,138,","272,799,777,"
67,2015,Mad Max: Fury Road,"367,457,874,","153,636,354,","213,821,520,"
68,2014,Edge of Tomorrow,"367,028,980,","100,206,256,","266,822,724,"
69,2009,Terminator Salvation,"365,491,792,","125,322,469,","240,169,323,"
70,2019,Shazam!,"363,664,533,","140,371,656,","223,292,877,"
71,2018,The Nun,"363,391,647,","117,450,119,","245,941,528,"
72,2004,Ocean's Twelve,"362,989,076,","125,531,634,","237,457,442,"
73,2020,Tenet,"362,450,957,","58,504,105,","303,946,852,"
74,2013,The Hangover 3,"362,000,072,","112,200,072,","249,800,000,"
75,2005,Batman Begins,"358,858,124,","205,343,774,","153,514,350,"
76,1993,The Fugitive,"353,715,317,","183,875,760,","169,839,557,"
77,2013,The Great Gatsby,"353,640,419,","144,840,419,","208,800,000,"
78,2016,The Legend of Tarzan,"348,902,025,","126,643,061,","222,258,964,"
79,1995,Batman Forever,"336,529,144,","184,031,112,","152,498,032,"
80,2014,300: Rise of an Empire,"330,780,051,","106,580,051,","224,200,000,"
81,2000,The Perfect Storm,"328,711,434,","182,618,434,","146,093,000,"
82,1992,Lethal Weapon 3,"319,700,000,","144,731,527,","174,968,473,"
83,2012,Journey 2: The Mysterious Island,"318,146,162,","103,860,290,","214,285,872,"
84,2013,The Conjuring,"317,744,402,","137,400,141,","180,344,261,"
85,2004,The Polar Express,"312,719,437,","188,578,855,","124,140,582,"
86,2007,Ocean's Thirteen,"311,744,465,","117,144,465,","194,600,000,"
87,2017,The Lego Batman Movie,"310,570,560,","175,750,384,","134,820,176,"
88,2016,The Conjuring 2: The Enfield Poltergeist,"310,201,399,","102,470,008,","207,731,391,"
89,2009,The Blind Side,"305,705,794,","255,959,475,","49,746,319,"
90,2017,Annabelle: Creation,"305,384,865,","102,092,201,","203,292,664,"
91,2012,Wrath of the Titans,"305,270,083,","83,670,083,","221,600,000,"
92,1978,Superman,"300,200,000,","134,218,018,","165,981,982,"
93,2018,Oceanâ€™s 8,"297,718,711,","140,218,711,","157,500,000,"
94,2010,Sex and the City 2,"294,680,778,","95,347,692,","199,333,086,"
95,1999,The Green Mile,"290,701,374,","136,801,374,","153,900,000,"
96,2006,The Departed,"289,660,619,","132,384,315,","157,276,304,"
97,1998,Lethal Weapon 4,"285,400,000,","130,444,603,","154,955,397,"
98,2002,Scooby-Doo,"276,294,164,","153,294,164,","123,000,000,"
99,2008,Gran Torino,"274,543,085","148,095,302","126,447,783"

# MERGE SUCCESS LET'S UPLOAD IT

The below will make a new csv file for us

In [34]:
warner_bros_csv.to_csv('warner_bros_cleaned.csv')

A small check

In [36]:
pd.read_csv('./warner_bros_cleaned.csv')

,Unnamed: 0,year,movie name,worldwide box office,domestic box office,international box office
0,0,2011,Harry Potter and the Deathly Hallows: Part II,"1,328,766,590,","381,193,157,","947,573,433,"
1,1,2018,Aquaman,"1,143,758,700,","335,061,807,","808,696,893,"
2,2,2012,The Dark Knight Rises,"1,082,228,107,","448,139,099,","634,089,008,"
3,3,2019,Joker,"1,072,507,517,","335,451,311,","737,056,206,"
4,4,2012,The Hobbit: An Unexpected Journey,"1,014,938,545,","303,003,568,","711,934,977,"
5,5,2008,The Dark Knight,"998,615,789,","533,720,947,","464,894,842,"
6,6,2001,Harry Potter and the Sorcererâ€™s Stone,"965,054,122,","317,871,467,","647,182,655,"
7,7,2013,The Hobbit: The Desolation of Smaug,"959,358,436,","258,241,522,","701,116,914,"
8,8,2010,Harry Potter and the Deathly Hallows: Part I,"952,601,389,","296,131,568,","656,469,821,"
9,9,2014,The Hobbit: The Battle of the Five Armies,"940,389,558,","255,119,788,","685,269,770,"
10,10,2007,Harry Potter and the Order of the Phoenix,"939,619,849,","292,137,260,","647,482,589,"
11,11,2009,Harry Potter and the Half-Blood Prince,"929,411,069,","302,089,278,","627,321,791,"
12,12,2005,Harry Potter and the Goblet of Fire,"886,746,240,","290,201,752,","596,544,488,"
13,13,2002,Harry Potter and the Chamber of Secrets,"875,262,553,","262,233,381,","613,029,172,"
14,14,2016,Batman v Superman: Dawn of Justice,"872,395,091,","330,360,194,","542,034,897,"
15,15,2017,Wonder Woman,"818,058,221,","412,563,408,","405,494,813,"
16,16,2016,Fantastic Beasts and Where to Find Them,"811,724,385,","234,037,575,","577,686,810,"
17,17,2004,Harry Potter and the Prisoner of Azkaban,"789,592,708,","249,757,726,","539,834,982,"
18,18,2022,The Batman,"768,159,998,","369,345,583,","398,814,415,"
19,19,2016,Suicide Squad,"745,744,980,","325,100,054,","420,644,926,"
20,20,2003,The Matrix Reloaded,"738,576,929,","281,553,689,","457,023,240,"
21,21,2010,Inception,"728,582,465,","292,576,195,","436,006,270,"
22,22,2017,It,"701,083,042,","328,828,874,","372,254,168,"
23,23,2013,Gravity,"688,214,291,","274,092,705,","414,121,586,"
24,24,2013,Man of Steel,"667,999,518,","291,045,518,","376,954,000,"
25,25,2017,Justice League,"655,945,209,","229,024,295,","426,920,914,"
26,26,2018,Fantastic Beasts: The Crimes of Grindelwald,"648,455,339,","159,555,901,","488,899,438,"
27,27,2011,The Hangover Part II,"586,764,305,","254,464,305,","332,300,000,"
28,28,2007,I am Legend,"585,532,684,","256,393,010,","329,139,674,"
29,29,2018,Ready Player One,"579,055,653,","137,690,172,","441,365,481,"
30,30,2017,Kong: Skull Island,"561,072,059,","168,052,812,","393,019,247,"
31,31,2014,American Sniper,"547,326,372,","350,126,372,","197,200,000,"
32,32,2018,Tang Ren Jie Tan An 2,"544,068,574,","1,983,984,","542,084,590,"
33,33,2011,Sherlock Holmes: A Game of Shadows,"535,663,443,","186,848,418,","348,815,025,"
34,34,2014,Godzilla,"529,076,069,","200,676,069,","328,400,000,"
35,35,2018,The Meg,"527,370,715,","145,443,742,","381,926,973,"
36,36,2017,Dunkirk,"518,058,826,","190,068,280,","327,990,546,"
37,37,2009,Sherlock Holmes,"498,438,212,","209,028,679,","289,409,533,"
38,38,1996,Twister,"495,700,000,","241,688,385,","254,011,615,"
39,39,2010,Clash of the Titans,"493,214,888,","163,214,888,","330,000,000,"
40,40,2004,Troy,"483,152,040,","133,298,577,","349,853,463,"
41,41,2005,Charlie and the Chocolate Factory,"475,825,484,","206,459,076,","269,366,408,"
42,42,2019,It: Chapter Two,"469,566,806,","211,593,228,","257,973,578,"
43,43,2014,The Lego Movie,"468,084,718,","257,784,718,","210,300,000,"
44,44,2021,Godzilla vs. Kong,"468,064,628,","100,916,094,","367,148,534,"
45,45,1999,The Matrix,"465,974,198,","173,993,387,","291,980,811,"
46,46,2009,The Hangover,"465,487,583,","277,322,503,","188,165,080,"
47,47,2003,The Last Samurai,"456,810,575,","111,110,575,","345,700,000,"
48,48,2015,San Andreas,"456,258,539,","155,190,832,","301,067,707,"
49,49,2007,300,"454,161,935,","210,614,939,","243,546,996,"
50,50,2001,Ocean's Eleven,"450,728,529,","183,417,150,","267,311,379,"
51,51,2003,Terminator 3: Rise of the Machines,"433,058,296,","150,358,296,","282,700,000,"
52,52,2018,A Star is Born,"431,870,523,","215,288,866,","216,581,657,"
53,53,2019,PokÃ©mon: Detective Pikachu,"431,344,168,","144,105,346,","287,238,822,"
54,54,1973,The Exorcist,"428,214,478,","230,347,346,","197,867,132,"
55,55,2018,Rampage,"427,947,217,","101,028,233,","326,918,984,"
56,56,2003,The Matrix Revolutions,"427,300,260,","139,270,910,","288,029,350,"
57,57,2008,Sex and the City,"415,247,258,","152,647,258,","262,600,000,"
58,58,1989,Batman,"411,348,924,","251,188,924,","160,160,000,"
59,59,2013,Pacific Rim,"411,002,906,","101,802,906,","309,200,000,"
60,60,1992,The Bodyguard,"410,945,720,","121,945,720,","289,000,000,"
61,61,2022,Fantastic Beasts: The Secrets of Dumbledore,"398,848,696,","95,850,844,","302,997,852,"
62,62,2021,Dune,"398,601,500,","108,327,830,","290,273,670,"
63,63,2006,Superman Returns,"391,081,192,","200,120,000,","190,961,192,"
64,64,1991,Robin Hood: Prince of Thieves,"390,500,000,","165,493,908,","225,006,092,"
65,65,2006,Happy Feet,"385,000,317,","198,000,317,","187,000,000,"
66,66,2019,Godzilla: King of the Monsters,"383,299,915,","110,500,138,","272,799,777,"
67,67,2015,Mad Max: Fury Road,"367,457,874,","153,636,354,","213,821,520,"
68,68,2014,Edge of Tomorrow,"367,028,980,","100,206,256,","266,822,724,"
69,69,2009,Terminator Salvation,"365,491,792,","125,322,469,","240,169,323,"
70,70,2019,Shazam!,"363,664,533,","140,371,656,","223,292,877,"
71,71,2018,The Nun,"363,391,647,","117,450,119,","245,941,528,"
72,72,2004,Ocean's Twelve,"362,989,076,","125,531,634,","237,457,442,"
73,73,2020,Tenet,"362,450,957,","58,504,105,","303,946,852,"
74,74,2013,The Hangover 3,"362,000,072,","112,200,072,","249,800,000,"
75,75,2005,Batman Begins,"358,858,124,","205,343,774,","153,514,350,"
76,76,1993,The Fugitive,"353,715,317,","183,875,760,","169,839,557,"
77,77,2013,The Great Gatsby,"353,640,419,","144,840,419,","208,800,000,"
78,78,2016,The Legend of Tarzan,"348,902,025,","126,643,061,","222,258,964,"
79,79,1995,Batman Forever,"336,529,144,","184,031,112,","152,498,032,"
80,80,2014,300: Rise of an Empire,"330,780,051,","106,580,051,","224,200,000,"
81,81,2000,The Perfect Storm,"328,711,434,","182,618,434,","146,093,000,"
82,82,1992,Lethal Weapon 3,"319,700,000,","144,731,527,","174,968,473,"
83,83,2012,Journey 2: The Mysterious Island,"318,146,162,","103,860,290,","214,285,872,"
84,84,2013,The Conjuring,"317,744,402,","137,400,141,","180,344,261,"
85,85,2004,The Polar Express,"312,719,437,","188,578,855,","124,140,582,"
86,86,2007,Ocean's Thirteen,"311,744,465,","117,144,465,","194,600,000,"
87,87,2017,The Lego Batman Movie,"310,570,560,","175,750,384,","134,820,176,"
88,88,2016,The Conjuring 2: The Enfield Poltergeist,"310,201,399,","102,470,008,","207,731,391,"
89,89,2009,The Blind Side,"305,705,794,","255,959,475,","49,746,319,"
90,90,2017,Annabelle: Creation,"305,384,865,","102,092,201,","203,292,664,"
91,91,2012,Wrath of the Titans,"305,270,083,","83,670,083,","221,600,000,"
92,92,1978,Superman,"300,200,000,","134,218,018,","165,981,982,"
93,93,2018,Oceanâ€™s 8,"297,718,711,","140,218,711,","157,500,000,"
94,94,2010,Sex and the City 2,"294,680,778,","95,347,692,","199,333,086,"
95,95,1999,The Green Mile,"290,701,374,","136,801,374,","153,900,000,"
96,96,2006,The Departed,"289,660,619,","132,384,315,","157,276,304,"
97,97,1998,Lethal Weapon 4,"285,400,000,","130,444,603,","154,955,397,"
98,98,2002,Scooby-Doo,"276,294,164,","153,294,164,","123,000,000,"
99,99,2008,Gran Torino,"274,543,085","148,095,302","126,447,783"