# Universal Data Clean from Scrapy Scrape

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./universal.csv')

In [3]:
df

,year released,movie name,worldwide box,domestic box,international box
0,"2015,2015,2018,2017,2015,1993,2017,2013,2016,2...","Jurassic World,Furious 7,Jurassic World: Falle...","$1,669,979,967,$1,514,553,486,$1,308,334,005,$...","$652,306,625,$353,007,020,$417,719,760,$225,76...","$1,017,673,342,$1,161,546,466,$890,614,245,$1,..."

# Time to Clean it up!

In [4]:
df['year released']

0    2015,2015,2018,2017,2015,1993,2017,2013,2016,2...
Name: year released, dtype: object

In [5]:
years_expanded = df['year released'].str.split(',', expand=True)

Reshape data for merge in the end!

In [6]:
a = years_expanded.T
a

       0
0   2015
1   2015
2   2018
3   2017
4   2015
..   ...
95  2007
96  1999
97  2003
98  2009
99  2014

[100 rows x 1 columns]

In [7]:
movie_name_expanded = df['movie name'].str.split(',',expand=True)

In [8]:
b = movie_name_expanded.T
b

                                 0
0                   Jurassic World
1                        Furious 7
2   Jurassic World: Fallen Kingdom
3          The Fate of the Furious
4                          Minions
..                             ...
95            Mr. Beanâ€™s Holiday
96                    American Pie
97                American Wedding
98              Itâ€™s Complicated
99                        Non-Stop

[100 rows x 1 columns]

In [9]:
world_wide = df['worldwide box'].str.split("$", expand=True)

In [10]:
world_wide
c=world_wide.T
c.drop(0,inplace=True)

In [11]:
c.reset_index(inplace=True)
c

    index               0
0       1  1,669,979,967,
1       2  1,514,553,486,
2       3  1,308,334,005,
3       4  1,236,703,796,
4       5  1,159,631,140,
..    ...             ...
95     96    234,981,342,
96     97    234,723,148,
97     98    232,354,205,
98     99    224,614,744,
99    100     222,383,055

[100 rows x 2 columns]

In [12]:
domestic = df['domestic box'].str.split("$", expand=True)

In [13]:
d = domestic.T

In [14]:

d.drop(0,inplace=True)

In [15]:
d.reset_index(inplace=True)

In [16]:
d

    index             0
0       1  652,306,625,
1       2  353,007,020,
2       3  417,719,760,
3       4  225,764,765,
4       5  336,045,770,
..    ...           ...
95     96   33,302,167,
96     97  101,800,948,
97     98  104,354,205,
98     99  112,735,375,
99    100    91,742,160

[100 rows x 2 columns]

In [17]:
international = df['international box'].str.split("$", expand=True)

In [18]:
e=international.T

In [19]:
e.drop(0,inplace=True)

In [20]:
e.reset_index(inplace=True)

In [21]:
e

    index               0
0       1  1,017,673,342,
1       2  1,161,546,466,
2       3    890,614,245,
3       4  1,010,939,031,
4       5    823,585,370,
..    ...             ...
95     96    201,679,175,
96     97    132,922,200,
97     98    128,000,000,
98     99    111,879,369,
99    100     130,640,895

[100 rows x 2 columns]

# Time for the merge!

In [22]:
test = pd.concat([a,b], axis=1)

In [23]:
test

       0                               0
0   2015                  Jurassic World
1   2015                       Furious 7
2   2018  Jurassic World: Fallen Kingdom
3   2017         The Fate of the Furious
4   2015                         Minions
..   ...                             ...
95  2007            Mr. Beanâ€™s Holiday
96  1999                    American Pie
97  2003                American Wedding
98  2009              Itâ€™s Complicated
99  2014                        Non-Stop

[100 rows x 2 columns]

In [24]:
test2 = pd.concat([a,b,c,d,e], axis=1)

In [25]:
test2

,0,0,index,0,index,0,index,0
0,2015,Jurassic World,1,"1,669,979,967,",1,"652,306,625,",1,"1,017,673,342,"
1,2015,Furious 7,2,"1,514,553,486,",2,"353,007,020,",2,"1,161,546,466,"
2,2018,Jurassic World: Fallen Kingdom,3,"1,308,334,005,",3,"417,719,760,",3,"890,614,245,"
3,2017,The Fate of the Furious,4,"1,236,703,796,",4,"225,764,765,",4,"1,010,939,031,"
4,2015,Minions,5,"1,159,631,140,",5,"336,045,770,",5,"823,585,370,"
...,...,...,...,...,...,...,...,...
95,2007,Mr. Beanâ€™s Holiday,96,"234,981,342,",96,"33,302,167,",96,"201,679,175,"
96,1999,American Pie,97,"234,723,148,",97,"101,800,948,",97,"132,922,200,"
97,2003,American Wedding,98,"232,354,205,",98,"104,354,205,",98,"128,000,000,"
98,2009,Itâ€™s Complicated,99,"224,614,744,",99,"112,735,375,",99,"111,879,369,"
99,2014,Non-Stop,100,"222,383,055",100,"91,742,160",100,"130,640,895"

In [26]:
pd. set_option('display.max_rows', None)

In [27]:
universal_csv = test2

In [28]:
universal_csv

,0,0,index,0,index,0,index,0
0,2015,Jurassic World,1,"1,669,979,967,",1,"652,306,625,",1,"1,017,673,342,"
1,2015,Furious 7,2,"1,514,553,486,",2,"353,007,020,",2,"1,161,546,466,"
2,2018,Jurassic World: Fallen Kingdom,3,"1,308,334,005,",3,"417,719,760,",3,"890,614,245,"
3,2017,The Fate of the Furious,4,"1,236,703,796,",4,"225,764,765,",4,"1,010,939,031,"
4,2015,Minions,5,"1,159,631,140,",5,"336,045,770,",5,"823,585,370,"
5,1993,Jurassic Park,6,"1,045,573,035,",6,"402,523,348,",6,"643,049,687,"
6,2017,Despicable Me 3,7,"1,032,961,987,",7,"264,624,300,",7,"768,337,687,"
7,2013,Despicable Me 2,8,"975,216,835,",8,"368,065,385,",8,"607,151,450,"
8,2016,The Secret Life of Pets,9,"885,302,500,",9,"368,384,330,",9,"516,918,170,"
9,2022,Jurassic World: Dominion,10,"877,674,210,",10,"351,528,210,",10,"526,146,000,"
10,1982,E.T. the Extra-Terrestrial,11,"792,962,972,",11,"435,110,554,",11,"357,852,418,"
11,2013,Fast and Furious 6,12,"789,300,444,",12,"238,679,850,",12,"550,620,594,"
12,2019,Fast & Furious Presents: Hobbs & Shaw,13,"760,381,706,",13,"173,956,935,",13,"586,424,771,"
13,2021,F9: The Fast Saga,14,"721,077,945,",14,"173,005,945,",14,"548,072,000,"
14,2016,Sing,15,"631,064,182,",15,"270,329,045,",15,"360,735,137,"
15,2011,Fast Five,16,"630,163,454,",16,"210,031,325,",16,"420,132,129,"
16,1997,The Lost World: Jurassic Park,17,"618,638,999,",17,"229,086,679,",17,"389,552,320,"
17,2008,Mamma Mia!,18,"598,421,187,",18,"144,130,063,",18,"454,291,124,"
18,2015,Fifty Shades of Grey,19,"570,794,950,",19,"166,167,230,",19,"404,627,720,"
19,2012,Ted,20,"556,016,627,",20,"218,665,740,",20,"337,350,887,"
20,2005,King Kong,21,"550,517,357,",21,"218,080,025,",21,"332,437,332,"
21,2010,Despicable Me,22,"543,464,573,",22,"251,513,985,",22,"291,950,588,"
22,2019,How to Train Your Dragon: The Hidden World,23,"521,214,344,",23,"160,799,505,",23,"360,414,839,"
23,2004,Meet the Fockers,24,"516,567,575,",24,"279,167,575,",24,"237,400,000,"
24,2018,Dr. Seussâ€™ The Grinch,25,"513,537,178,",25,"270,834,950,",25,"242,702,228,"
25,2003,Bruce Almighty,26,"484,468,608,",26,"242,704,995,",26,"241,763,613,"
26,1975,Jaws,27,"470,700,000,",27,"260,000,000,",27,"210,700,000,"
27,2014,Lucy,28,"457,507,776,",28,"126,573,960,",28,"330,933,816,"
28,2019,The Secret Life of Pets 2,29,"446,277,935,",29,"158,874,395,",29,"287,403,540,"
29,2007,The Bourne Ultimatum,30,"444,043,396,",30,"227,471,070,",30,"216,572,326,"
30,2016,Warcraft,31,"438,899,824,",31,"47,365,290,",31,"391,534,534,"
31,2012,Les MisÃ©rables,32,"438,420,442,",32,"148,809,770,",32,"289,610,672,"
32,2001,The Mummy Returns,33,"435,040,395,",33,"202,007,640,",33,"233,032,755,"
33,1999,The Mummy,34,"416,385,488,",34,"155,385,488,",34,"261,000,000,"
34,2016,Jason Bourne,35,"416,168,316,",35,"162,192,920,",35,"253,975,396,"
35,2017,The Mummy,36,"409,953,905,",36,"80,101,125,",36,"329,852,780,"
36,2022,Minions: The Rise of Gru,37,"406,753,660,",37,"216,948,660,",37,"189,805,000,"
37,2008,The Mummy: Tomb of the Dragon Emperor,38,"405,760,225,",38,"102,491,776,",38,"303,268,449,"
38,2021,Sing 2,39,"402,749,901,",39,"162,790,990,",39,"239,958,911,"
39,2012,Snow White and the Huntsman,40,"401,021,746,",40,"155,136,755,",40,"245,884,991,"
40,2018,Mamma Mia: Here We Go Again!,41,"399,228,127,",41,"120,634,935,",41,"278,593,192,"
41,1985,Back to the Future,42,"385,510,205,",42,"212,259,762,",42,"173,250,443,"
42,2017,Fifty Shades Darker,43,"381,367,046,",43,"114,434,010,",43,"266,933,036,"
43,2018,Fifty Shades Freed,44,"371,985,018,",44,"100,407,760,",44,"271,577,258,"
44,2019,1917,45,"370,603,379,",45,"159,227,644,",45,"211,375,735,"
45,2001,Jurassic Park III,46,"365,900,000,",46,"181,166,115,",46,"184,733,885,"
46,1999,Notting Hill,47,"363,718,196,",47,"116,089,678,",47,"247,628,518,"
47,2009,Fast & Furious,48,"359,347,833,",48,"155,064,265,",48,"204,283,568,"
48,1994,The Flintstones,49,"358,500,000,",49,"130,531,208,",49,"227,968,792,"
49,2012,Dr. Seussâ€™ The Lorax,50,"350,976,753,",50,"214,030,500,",50,"136,946,253,"
50,2000,How the Grinch Stole Christmas,51,"345,445,403,",51,"260,348,825,",51,"85,096,578,"
51,2008,Wanted,52,"342,416,460,",52,"134,508,551,",52,"207,907,909,"
52,1995,Apollo 13,53,"335,802,271,",53,"173,772,767,",53,"162,029,504,"
53,2016,The Great Wall,54,"334,486,852,",54,"45,157,105,",54,"289,329,747,"
54,1989,Back to the Future Part II,55,"331,971,881,",55,"118,450,002,",55,"213,521,879,"
55,2000,Meet the Parents,56,"330,425,040,",56,"166,225,040,",56,"164,200,000,"
56,2010,Robin Hood,57,"322,459,006,",57,"105,487,148,",57,"216,971,858,"
57,1993,Schindlerâ€™s List,58,"322,197,132,",58,"96,898,818,",58,"225,298,314,"
58,2018,Green Book,59,"319,993,551,",59,"85,080,171,",59,"234,913,380,"
59,2001,A Beautiful Mind,60,"317,668,058,",60,"170,708,996,",60,"146,959,062,"
60,2012,Battleship,61,"313,477,717,",61,"65,233,400,",61,"248,244,317,"
61,2004,The Bourne Supremacy,62,"311,001,124,",62,"176,087,450,",62,"134,913,674,"
62,2010,Little Fockers,63,"310,650,574,",63,"148,438,600,",63,"162,211,974,"
63,2018,Skyscraper,64,"304,868,961,",64,"68,420,120,",64,"236,448,841,"
64,1997,Liar Liar,65,"302,710,615,",65,"181,410,615,",65,"121,300,000,"
65,2004,Van Helsing,66,"300,150,546,",66,"120,150,546,",66,"180,000,000,"
66,2018,Pacific Rim: Uprising,67,"290,930,148,",67,"59,874,525,",67,"231,055,623,"
67,2011,Bridesmaids,68,"289,632,023,",68,"169,211,718,",68,"120,420,305,"
68,2013,Oblivion,69,"287,916,633,",69,"89,107,235,",69,"198,809,398,"
69,2015,Pitch Perfect 2,70,"287,215,196,",70,"184,296,230,",70,"102,918,966,"
70,2001,American Pie 2,71,"286,500,000,",71,"145,096,820,",71,"141,403,180,"
71,1995,Casper,72,"282,300,000,",72,"100,328,194,",72,"181,971,806,"
72,2012,The Bourne Legacy,73,"280,355,920,",73,"113,203,870,",73,"167,152,050,"
73,2017,Split,74,"278,754,594,",74,"138,141,585,",74,"140,613,009,"
74,1996,The Nutty Professor,75,"273,814,019,",75,"128,814,019,",75,"145,000,000,"
75,2014,Neighbors,76,"270,944,428,",76,"150,086,800,",76,"120,857,628,"
76,2007,American Gangster,77,"267,985,456,",77,"130,164,645,",77,"137,820,811,"
77,2008,The Incredible Hulk,78,"265,573,859,",78,"134,806,913,",78,"130,766,946,"
78,1995,Waterworld,79,"264,246,220,",79,"88,246,220,",79,"176,000,000,"
79,2004,Bridget Jones: The Edge Of Reason,80,"263,894,551,",80,"40,203,020,",80,"223,691,531,"
80,1985,Out of Africa,81,"258,210,860,",81,"79,096,868,",81,"179,113,992,"
81,2000,Erin Brockovich,82,"257,805,243,",82,"125,548,685,",82,"132,256,558,"
82,2019,Us,83,"256,091,919,",83,"175,084,580,",83,"81,007,339,"
83,2018,Halloween,84,"255,416,089,",84,"159,366,015,",84,"96,050,074,"
84,2017,Get Out,85,"252,297,405,",85,"175,837,935,",85,"76,459,470,"
85,2020,Dolittle,86,"251,410,631,",86,"77,047,065,",86,"174,363,566,"
86,2019,Glass,87,"246,999,039,",87,"111,048,468,",87,"135,950,571,"
87,2003,Love Actually,88,"246,671,987,",88,"59,472,278,",88,"187,199,709,"
88,1995,Babe,89,"246,100,000,",89,"63,658,910,",89,"182,441,090,"
89,2002,8 Mile,90,"245,768,384,",90,"116,724,075,",90,"129,044,309,"
90,2003,Hulk,91,"245,031,679,",91,"132,177,234,",91,"112,854,445,"
91,2022,The Bad Guys,92,"244,384,040,",92,"96,393,095,",92,"147,990,945,"
92,1990,Back to the Future Part III,93,"244,087,268,",93,"88,055,283,",93,"156,031,985,"
93,2012,American Reunion,94,"236,799,211,",94,"56,758,835,",94,"180,040,376,"
94,2003,2 Fast 2 Furious,95,"236,410,607,",95,"127,120,058,",95,"109,290,549,"
95,2007,Mr. Beanâ€™s Holiday,96,"234,981,342,",96,"33,302,167,",96,"201,679,175,"
96,1999,American Pie,97,"234,723,148,",97,"101,800,948,",97,"132,922,200,"
97,2003,American Wedding,98,"232,354,205,",98,"104,354,205,",98,"128,000,000,"
98,2009,Itâ€™s Complicated,99,"224,614,744,",99,"112,735,375,",99,"111,879,369,"
99,2014,Non-Stop,100,"222,383,055",100,"91,742,160",100,"130,640,895"

Delete useless column!

In [29]:
del universal_csv['index']

In [30]:
universal_csv

,0,0,0,0,0
0,2015,Jurassic World,"1,669,979,967,","652,306,625,","1,017,673,342,"
1,2015,Furious 7,"1,514,553,486,","353,007,020,","1,161,546,466,"
2,2018,Jurassic World: Fallen Kingdom,"1,308,334,005,","417,719,760,","890,614,245,"
3,2017,The Fate of the Furious,"1,236,703,796,","225,764,765,","1,010,939,031,"
4,2015,Minions,"1,159,631,140,","336,045,770,","823,585,370,"
5,1993,Jurassic Park,"1,045,573,035,","402,523,348,","643,049,687,"
6,2017,Despicable Me 3,"1,032,961,987,","264,624,300,","768,337,687,"
7,2013,Despicable Me 2,"975,216,835,","368,065,385,","607,151,450,"
8,2016,The Secret Life of Pets,"885,302,500,","368,384,330,","516,918,170,"
9,2022,Jurassic World: Dominion,"877,674,210,","351,528,210,","526,146,000,"
10,1982,E.T. the Extra-Terrestrial,"792,962,972,","435,110,554,","357,852,418,"
11,2013,Fast and Furious 6,"789,300,444,","238,679,850,","550,620,594,"
12,2019,Fast & Furious Presents: Hobbs & Shaw,"760,381,706,","173,956,935,","586,424,771,"
13,2021,F9: The Fast Saga,"721,077,945,","173,005,945,","548,072,000,"
14,2016,Sing,"631,064,182,","270,329,045,","360,735,137,"
15,2011,Fast Five,"630,163,454,","210,031,325,","420,132,129,"
16,1997,The Lost World: Jurassic Park,"618,638,999,","229,086,679,","389,552,320,"
17,2008,Mamma Mia!,"598,421,187,","144,130,063,","454,291,124,"
18,2015,Fifty Shades of Grey,"570,794,950,","166,167,230,","404,627,720,"
19,2012,Ted,"556,016,627,","218,665,740,","337,350,887,"
20,2005,King Kong,"550,517,357,","218,080,025,","332,437,332,"
21,2010,Despicable Me,"543,464,573,","251,513,985,","291,950,588,"
22,2019,How to Train Your Dragon: The Hidden World,"521,214,344,","160,799,505,","360,414,839,"
23,2004,Meet the Fockers,"516,567,575,","279,167,575,","237,400,000,"
24,2018,Dr. Seussâ€™ The Grinch,"513,537,178,","270,834,950,","242,702,228,"
25,2003,Bruce Almighty,"484,468,608,","242,704,995,","241,763,613,"
26,1975,Jaws,"470,700,000,","260,000,000,","210,700,000,"
27,2014,Lucy,"457,507,776,","126,573,960,","330,933,816,"
28,2019,The Secret Life of Pets 2,"446,277,935,","158,874,395,","287,403,540,"
29,2007,The Bourne Ultimatum,"444,043,396,","227,471,070,","216,572,326,"
30,2016,Warcraft,"438,899,824,","47,365,290,","391,534,534,"
31,2012,Les MisÃ©rables,"438,420,442,","148,809,770,","289,610,672,"
32,2001,The Mummy Returns,"435,040,395,","202,007,640,","233,032,755,"
33,1999,The Mummy,"416,385,488,","155,385,488,","261,000,000,"
34,2016,Jason Bourne,"416,168,316,","162,192,920,","253,975,396,"
35,2017,The Mummy,"409,953,905,","80,101,125,","329,852,780,"
36,2022,Minions: The Rise of Gru,"406,753,660,","216,948,660,","189,805,000,"
37,2008,The Mummy: Tomb of the Dragon Emperor,"405,760,225,","102,491,776,","303,268,449,"
38,2021,Sing 2,"402,749,901,","162,790,990,","239,958,911,"
39,2012,Snow White and the Huntsman,"401,021,746,","155,136,755,","245,884,991,"
40,2018,Mamma Mia: Here We Go Again!,"399,228,127,","120,634,935,","278,593,192,"
41,1985,Back to the Future,"385,510,205,","212,259,762,","173,250,443,"
42,2017,Fifty Shades Darker,"381,367,046,","114,434,010,","266,933,036,"
43,2018,Fifty Shades Freed,"371,985,018,","100,407,760,","271,577,258,"
44,2019,1917,"370,603,379,","159,227,644,","211,375,735,"
45,2001,Jurassic Park III,"365,900,000,","181,166,115,","184,733,885,"
46,1999,Notting Hill,"363,718,196,","116,089,678,","247,628,518,"
47,2009,Fast & Furious,"359,347,833,","155,064,265,","204,283,568,"
48,1994,The Flintstones,"358,500,000,","130,531,208,","227,968,792,"
49,2012,Dr. Seussâ€™ The Lorax,"350,976,753,","214,030,500,","136,946,253,"
50,2000,How the Grinch Stole Christmas,"345,445,403,","260,348,825,","85,096,578,"
51,2008,Wanted,"342,416,460,","134,508,551,","207,907,909,"
52,1995,Apollo 13,"335,802,271,","173,772,767,","162,029,504,"
53,2016,The Great Wall,"334,486,852,","45,157,105,","289,329,747,"
54,1989,Back to the Future Part II,"331,971,881,","118,450,002,","213,521,879,"
55,2000,Meet the Parents,"330,425,040,","166,225,040,","164,200,000,"
56,2010,Robin Hood,"322,459,006,","105,487,148,","216,971,858,"
57,1993,Schindlerâ€™s List,"322,197,132,","96,898,818,","225,298,314,"
58,2018,Green Book,"319,993,551,","85,080,171,","234,913,380,"
59,2001,A Beautiful Mind,"317,668,058,","170,708,996,","146,959,062,"
60,2012,Battleship,"313,477,717,","65,233,400,","248,244,317,"
61,2004,The Bourne Supremacy,"311,001,124,","176,087,450,","134,913,674,"
62,2010,Little Fockers,"310,650,574,","148,438,600,","162,211,974,"
63,2018,Skyscraper,"304,868,961,","68,420,120,","236,448,841,"
64,1997,Liar Liar,"302,710,615,","181,410,615,","121,300,000,"
65,2004,Van Helsing,"300,150,546,","120,150,546,","180,000,000,"
66,2018,Pacific Rim: Uprising,"290,930,148,","59,874,525,","231,055,623,"
67,2011,Bridesmaids,"289,632,023,","169,211,718,","120,420,305,"
68,2013,Oblivion,"287,916,633,","89,107,235,","198,809,398,"
69,2015,Pitch Perfect 2,"287,215,196,","184,296,230,","102,918,966,"
70,2001,American Pie 2,"286,500,000,","145,096,820,","141,403,180,"
71,1995,Casper,"282,300,000,","100,328,194,","181,971,806,"
72,2012,The Bourne Legacy,"280,355,920,","113,203,870,","167,152,050,"
73,2017,Split,"278,754,594,","138,141,585,","140,613,009,"
74,1996,The Nutty Professor,"273,814,019,","128,814,019,","145,000,000,"
75,2014,Neighbors,"270,944,428,","150,086,800,","120,857,628,"
76,2007,American Gangster,"267,985,456,","130,164,645,","137,820,811,"
77,2008,The Incredible Hulk,"265,573,859,","134,806,913,","130,766,946,"
78,1995,Waterworld,"264,246,220,","88,246,220,","176,000,000,"
79,2004,Bridget Jones: The Edge Of Reason,"263,894,551,","40,203,020,","223,691,531,"
80,1985,Out of Africa,"258,210,860,","79,096,868,","179,113,992,"
81,2000,Erin Brockovich,"257,805,243,","125,548,685,","132,256,558,"
82,2019,Us,"256,091,919,","175,084,580,","81,007,339,"
83,2018,Halloween,"255,416,089,","159,366,015,","96,050,074,"
84,2017,Get Out,"252,297,405,","175,837,935,","76,459,470,"
85,2020,Dolittle,"251,410,631,","77,047,065,","174,363,566,"
86,2019,Glass,"246,999,039,","111,048,468,","135,950,571,"
87,2003,Love Actually,"246,671,987,","59,472,278,","187,199,709,"
88,1995,Babe,"246,100,000,","63,658,910,","182,441,090,"
89,2002,8 Mile,"245,768,384,","116,724,075,","129,044,309,"
90,2003,Hulk,"245,031,679,","132,177,234,","112,854,445,"
91,2022,The Bad Guys,"244,384,040,","96,393,095,","147,990,945,"
92,1990,Back to the Future Part III,"244,087,268,","88,055,283,","156,031,985,"
93,2012,American Reunion,"236,799,211,","56,758,835,","180,040,376,"
94,2003,2 Fast 2 Furious,"236,410,607,","127,120,058,","109,290,549,"
95,2007,Mr. Beanâ€™s Holiday,"234,981,342,","33,302,167,","201,679,175,"
96,1999,American Pie,"234,723,148,","101,800,948,","132,922,200,"
97,2003,American Wedding,"232,354,205,","104,354,205,","128,000,000,"
98,2009,Itâ€™s Complicated,"224,614,744,","112,735,375,","111,879,369,"
99,2014,Non-Stop,"222,383,055","91,742,160","130,640,895"

Rename Columns!

In [31]:
universal_csv.columns=['year','movie name','worldwide box office','domestic box office','international box office']

In [32]:
universal_csv

,year,movie name,worldwide box office,domestic box office,international box office
0,2015,Jurassic World,"1,669,979,967,","652,306,625,","1,017,673,342,"
1,2015,Furious 7,"1,514,553,486,","353,007,020,","1,161,546,466,"
2,2018,Jurassic World: Fallen Kingdom,"1,308,334,005,","417,719,760,","890,614,245,"
3,2017,The Fate of the Furious,"1,236,703,796,","225,764,765,","1,010,939,031,"
4,2015,Minions,"1,159,631,140,","336,045,770,","823,585,370,"
5,1993,Jurassic Park,"1,045,573,035,","402,523,348,","643,049,687,"
6,2017,Despicable Me 3,"1,032,961,987,","264,624,300,","768,337,687,"
7,2013,Despicable Me 2,"975,216,835,","368,065,385,","607,151,450,"
8,2016,The Secret Life of Pets,"885,302,500,","368,384,330,","516,918,170,"
9,2022,Jurassic World: Dominion,"877,674,210,","351,528,210,","526,146,000,"
10,1982,E.T. the Extra-Terrestrial,"792,962,972,","435,110,554,","357,852,418,"
11,2013,Fast and Furious 6,"789,300,444,","238,679,850,","550,620,594,"
12,2019,Fast & Furious Presents: Hobbs & Shaw,"760,381,706,","173,956,935,","586,424,771,"
13,2021,F9: The Fast Saga,"721,077,945,","173,005,945,","548,072,000,"
14,2016,Sing,"631,064,182,","270,329,045,","360,735,137,"
15,2011,Fast Five,"630,163,454,","210,031,325,","420,132,129,"
16,1997,The Lost World: Jurassic Park,"618,638,999,","229,086,679,","389,552,320,"
17,2008,Mamma Mia!,"598,421,187,","144,130,063,","454,291,124,"
18,2015,Fifty Shades of Grey,"570,794,950,","166,167,230,","404,627,720,"
19,2012,Ted,"556,016,627,","218,665,740,","337,350,887,"
20,2005,King Kong,"550,517,357,","218,080,025,","332,437,332,"
21,2010,Despicable Me,"543,464,573,","251,513,985,","291,950,588,"
22,2019,How to Train Your Dragon: The Hidden World,"521,214,344,","160,799,505,","360,414,839,"
23,2004,Meet the Fockers,"516,567,575,","279,167,575,","237,400,000,"
24,2018,Dr. Seussâ€™ The Grinch,"513,537,178,","270,834,950,","242,702,228,"
25,2003,Bruce Almighty,"484,468,608,","242,704,995,","241,763,613,"
26,1975,Jaws,"470,700,000,","260,000,000,","210,700,000,"
27,2014,Lucy,"457,507,776,","126,573,960,","330,933,816,"
28,2019,The Secret Life of Pets 2,"446,277,935,","158,874,395,","287,403,540,"
29,2007,The Bourne Ultimatum,"444,043,396,","227,471,070,","216,572,326,"
30,2016,Warcraft,"438,899,824,","47,365,290,","391,534,534,"
31,2012,Les MisÃ©rables,"438,420,442,","148,809,770,","289,610,672,"
32,2001,The Mummy Returns,"435,040,395,","202,007,640,","233,032,755,"
33,1999,The Mummy,"416,385,488,","155,385,488,","261,000,000,"
34,2016,Jason Bourne,"416,168,316,","162,192,920,","253,975,396,"
35,2017,The Mummy,"409,953,905,","80,101,125,","329,852,780,"
36,2022,Minions: The Rise of Gru,"406,753,660,","216,948,660,","189,805,000,"
37,2008,The Mummy: Tomb of the Dragon Emperor,"405,760,225,","102,491,776,","303,268,449,"
38,2021,Sing 2,"402,749,901,","162,790,990,","239,958,911,"
39,2012,Snow White and the Huntsman,"401,021,746,","155,136,755,","245,884,991,"
40,2018,Mamma Mia: Here We Go Again!,"399,228,127,","120,634,935,","278,593,192,"
41,1985,Back to the Future,"385,510,205,","212,259,762,","173,250,443,"
42,2017,Fifty Shades Darker,"381,367,046,","114,434,010,","266,933,036,"
43,2018,Fifty Shades Freed,"371,985,018,","100,407,760,","271,577,258,"
44,2019,1917,"370,603,379,","159,227,644,","211,375,735,"
45,2001,Jurassic Park III,"365,900,000,","181,166,115,","184,733,885,"
46,1999,Notting Hill,"363,718,196,","116,089,678,","247,628,518,"
47,2009,Fast & Furious,"359,347,833,","155,064,265,","204,283,568,"
48,1994,The Flintstones,"358,500,000,","130,531,208,","227,968,792,"
49,2012,Dr. Seussâ€™ The Lorax,"350,976,753,","214,030,500,","136,946,253,"
50,2000,How the Grinch Stole Christmas,"345,445,403,","260,348,825,","85,096,578,"
51,2008,Wanted,"342,416,460,","134,508,551,","207,907,909,"
52,1995,Apollo 13,"335,802,271,","173,772,767,","162,029,504,"
53,2016,The Great Wall,"334,486,852,","45,157,105,","289,329,747,"
54,1989,Back to the Future Part II,"331,971,881,","118,450,002,","213,521,879,"
55,2000,Meet the Parents,"330,425,040,","166,225,040,","164,200,000,"
56,2010,Robin Hood,"322,459,006,","105,487,148,","216,971,858,"
57,1993,Schindlerâ€™s List,"322,197,132,","96,898,818,","225,298,314,"
58,2018,Green Book,"319,993,551,","85,080,171,","234,913,380,"
59,2001,A Beautiful Mind,"317,668,058,","170,708,996,","146,959,062,"
60,2012,Battleship,"313,477,717,","65,233,400,","248,244,317,"
61,2004,The Bourne Supremacy,"311,001,124,","176,087,450,","134,913,674,"
62,2010,Little Fockers,"310,650,574,","148,438,600,","162,211,974,"
63,2018,Skyscraper,"304,868,961,","68,420,120,","236,448,841,"
64,1997,Liar Liar,"302,710,615,","181,410,615,","121,300,000,"
65,2004,Van Helsing,"300,150,546,","120,150,546,","180,000,000,"
66,2018,Pacific Rim: Uprising,"290,930,148,","59,874,525,","231,055,623,"
67,2011,Bridesmaids,"289,632,023,","169,211,718,","120,420,305,"
68,2013,Oblivion,"287,916,633,","89,107,235,","198,809,398,"
69,2015,Pitch Perfect 2,"287,215,196,","184,296,230,","102,918,966,"
70,2001,American Pie 2,"286,500,000,","145,096,820,","141,403,180,"
71,1995,Casper,"282,300,000,","100,328,194,","181,971,806,"
72,2012,The Bourne Legacy,"280,355,920,","113,203,870,","167,152,050,"
73,2017,Split,"278,754,594,","138,141,585,","140,613,009,"
74,1996,The Nutty Professor,"273,814,019,","128,814,019,","145,000,000,"
75,2014,Neighbors,"270,944,428,","150,086,800,","120,857,628,"
76,2007,American Gangster,"267,985,456,","130,164,645,","137,820,811,"
77,2008,The Incredible Hulk,"265,573,859,","134,806,913,","130,766,946,"
78,1995,Waterworld,"264,246,220,","88,246,220,","176,000,000,"
79,2004,Bridget Jones: The Edge Of Reason,"263,894,551,","40,203,020,","223,691,531,"
80,1985,Out of Africa,"258,210,860,","79,096,868,","179,113,992,"
81,2000,Erin Brockovich,"257,805,243,","125,548,685,","132,256,558,"
82,2019,Us,"256,091,919,","175,084,580,","81,007,339,"
83,2018,Halloween,"255,416,089,","159,366,015,","96,050,074,"
84,2017,Get Out,"252,297,405,","175,837,935,","76,459,470,"
85,2020,Dolittle,"251,410,631,","77,047,065,","174,363,566,"
86,2019,Glass,"246,999,039,","111,048,468,","135,950,571,"
87,2003,Love Actually,"246,671,987,","59,472,278,","187,199,709,"
88,1995,Babe,"246,100,000,","63,658,910,","182,441,090,"
89,2002,8 Mile,"245,768,384,","116,724,075,","129,044,309,"
90,2003,Hulk,"245,031,679,","132,177,234,","112,854,445,"
91,2022,The Bad Guys,"244,384,040,","96,393,095,","147,990,945,"
92,1990,Back to the Future Part III,"244,087,268,","88,055,283,","156,031,985,"
93,2012,American Reunion,"236,799,211,","56,758,835,","180,040,376,"
94,2003,2 Fast 2 Furious,"236,410,607,","127,120,058,","109,290,549,"
95,2007,Mr. Beanâ€™s Holiday,"234,981,342,","33,302,167,","201,679,175,"
96,1999,American Pie,"234,723,148,","101,800,948,","132,922,200,"
97,2003,American Wedding,"232,354,205,","104,354,205,","128,000,000,"
98,2009,Itâ€™s Complicated,"224,614,744,","112,735,375,","111,879,369,"
99,2014,Non-Stop,"222,383,055","91,742,160","130,640,895"

# Mission Success! Import it!

In [33]:
universal_csv.to_csv('universal_cleaned.csv')

Just a check:

In [34]:
pd.read_csv('./universal_cleaned.csv')

,Unnamed: 0,year,movie name,worldwide box office,domestic box office,international box office
0,0,2015,Jurassic World,"1,669,979,967,","652,306,625,","1,017,673,342,"
1,1,2015,Furious 7,"1,514,553,486,","353,007,020,","1,161,546,466,"
2,2,2018,Jurassic World: Fallen Kingdom,"1,308,334,005,","417,719,760,","890,614,245,"
3,3,2017,The Fate of the Furious,"1,236,703,796,","225,764,765,","1,010,939,031,"
4,4,2015,Minions,"1,159,631,140,","336,045,770,","823,585,370,"
5,5,1993,Jurassic Park,"1,045,573,035,","402,523,348,","643,049,687,"
6,6,2017,Despicable Me 3,"1,032,961,987,","264,624,300,","768,337,687,"
7,7,2013,Despicable Me 2,"975,216,835,","368,065,385,","607,151,450,"
8,8,2016,The Secret Life of Pets,"885,302,500,","368,384,330,","516,918,170,"
9,9,2022,Jurassic World: Dominion,"877,674,210,","351,528,210,","526,146,000,"
10,10,1982,E.T. the Extra-Terrestrial,"792,962,972,","435,110,554,","357,852,418,"
11,11,2013,Fast and Furious 6,"789,300,444,","238,679,850,","550,620,594,"
12,12,2019,Fast & Furious Presents: Hobbs & Shaw,"760,381,706,","173,956,935,","586,424,771,"
13,13,2021,F9: The Fast Saga,"721,077,945,","173,005,945,","548,072,000,"
14,14,2016,Sing,"631,064,182,","270,329,045,","360,735,137,"
15,15,2011,Fast Five,"630,163,454,","210,031,325,","420,132,129,"
16,16,1997,The Lost World: Jurassic Park,"618,638,999,","229,086,679,","389,552,320,"
17,17,2008,Mamma Mia!,"598,421,187,","144,130,063,","454,291,124,"
18,18,2015,Fifty Shades of Grey,"570,794,950,","166,167,230,","404,627,720,"
19,19,2012,Ted,"556,016,627,","218,665,740,","337,350,887,"
20,20,2005,King Kong,"550,517,357,","218,080,025,","332,437,332,"
21,21,2010,Despicable Me,"543,464,573,","251,513,985,","291,950,588,"
22,22,2019,How to Train Your Dragon: The Hidden World,"521,214,344,","160,799,505,","360,414,839,"
23,23,2004,Meet the Fockers,"516,567,575,","279,167,575,","237,400,000,"
24,24,2018,Dr. Seussâ€™ The Grinch,"513,537,178,","270,834,950,","242,702,228,"
25,25,2003,Bruce Almighty,"484,468,608,","242,704,995,","241,763,613,"
26,26,1975,Jaws,"470,700,000,","260,000,000,","210,700,000,"
27,27,2014,Lucy,"457,507,776,","126,573,960,","330,933,816,"
28,28,2019,The Secret Life of Pets 2,"446,277,935,","158,874,395,","287,403,540,"
29,29,2007,The Bourne Ultimatum,"444,043,396,","227,471,070,","216,572,326,"
30,30,2016,Warcraft,"438,899,824,","47,365,290,","391,534,534,"
31,31,2012,Les MisÃ©rables,"438,420,442,","148,809,770,","289,610,672,"
32,32,2001,The Mummy Returns,"435,040,395,","202,007,640,","233,032,755,"
33,33,1999,The Mummy,"416,385,488,","155,385,488,","261,000,000,"
34,34,2016,Jason Bourne,"416,168,316,","162,192,920,","253,975,396,"
35,35,2017,The Mummy,"409,953,905,","80,101,125,","329,852,780,"
36,36,2022,Minions: The Rise of Gru,"406,753,660,","216,948,660,","189,805,000,"
37,37,2008,The Mummy: Tomb of the Dragon Emperor,"405,760,225,","102,491,776,","303,268,449,"
38,38,2021,Sing 2,"402,749,901,","162,790,990,","239,958,911,"
39,39,2012,Snow White and the Huntsman,"401,021,746,","155,136,755,","245,884,991,"
40,40,2018,Mamma Mia: Here We Go Again!,"399,228,127,","120,634,935,","278,593,192,"
41,41,1985,Back to the Future,"385,510,205,","212,259,762,","173,250,443,"
42,42,2017,Fifty Shades Darker,"381,367,046,","114,434,010,","266,933,036,"
43,43,2018,Fifty Shades Freed,"371,985,018,","100,407,760,","271,577,258,"
44,44,2019,1917,"370,603,379,","159,227,644,","211,375,735,"
45,45,2001,Jurassic Park III,"365,900,000,","181,166,115,","184,733,885,"
46,46,1999,Notting Hill,"363,718,196,","116,089,678,","247,628,518,"
47,47,2009,Fast & Furious,"359,347,833,","155,064,265,","204,283,568,"
48,48,1994,The Flintstones,"358,500,000,","130,531,208,","227,968,792,"
49,49,2012,Dr. Seussâ€™ The Lorax,"350,976,753,","214,030,500,","136,946,253,"
50,50,2000,How the Grinch Stole Christmas,"345,445,403,","260,348,825,","85,096,578,"
51,51,2008,Wanted,"342,416,460,","134,508,551,","207,907,909,"
52,52,1995,Apollo 13,"335,802,271,","173,772,767,","162,029,504,"
53,53,2016,The Great Wall,"334,486,852,","45,157,105,","289,329,747,"
54,54,1989,Back to the Future Part II,"331,971,881,","118,450,002,","213,521,879,"
55,55,2000,Meet the Parents,"330,425,040,","166,225,040,","164,200,000,"
56,56,2010,Robin Hood,"322,459,006,","105,487,148,","216,971,858,"
57,57,1993,Schindlerâ€™s List,"322,197,132,","96,898,818,","225,298,314,"
58,58,2018,Green Book,"319,993,551,","85,080,171,","234,913,380,"
59,59,2001,A Beautiful Mind,"317,668,058,","170,708,996,","146,959,062,"
60,60,2012,Battleship,"313,477,717,","65,233,400,","248,244,317,"
61,61,2004,The Bourne Supremacy,"311,001,124,","176,087,450,","134,913,674,"
62,62,2010,Little Fockers,"310,650,574,","148,438,600,","162,211,974,"
63,63,2018,Skyscraper,"304,868,961,","68,420,120,","236,448,841,"
64,64,1997,Liar Liar,"302,710,615,","181,410,615,","121,300,000,"
65,65,2004,Van Helsing,"300,150,546,","120,150,546,","180,000,000,"
66,66,2018,Pacific Rim: Uprising,"290,930,148,","59,874,525,","231,055,623,"
67,67,2011,Bridesmaids,"289,632,023,","169,211,718,","120,420,305,"
68,68,2013,Oblivion,"287,916,633,","89,107,235,","198,809,398,"
69,69,2015,Pitch Perfect 2,"287,215,196,","184,296,230,","102,918,966,"
70,70,2001,American Pie 2,"286,500,000,","145,096,820,","141,403,180,"
71,71,1995,Casper,"282,300,000,","100,328,194,","181,971,806,"
72,72,2012,The Bourne Legacy,"280,355,920,","113,203,870,","167,152,050,"
73,73,2017,Split,"278,754,594,","138,141,585,","140,613,009,"
74,74,1996,The Nutty Professor,"273,814,019,","128,814,019,","145,000,000,"
75,75,2014,Neighbors,"270,944,428,","150,086,800,","120,857,628,"
76,76,2007,American Gangster,"267,985,456,","130,164,645,","137,820,811,"
77,77,2008,The Incredible Hulk,"265,573,859,","134,806,913,","130,766,946,"
78,78,1995,Waterworld,"264,246,220,","88,246,220,","176,000,000,"
79,79,2004,Bridget Jones: The Edge Of Reason,"263,894,551,","40,203,020,","223,691,531,"
80,80,1985,Out of Africa,"258,210,860,","79,096,868,","179,113,992,"
81,81,2000,Erin Brockovich,"257,805,243,","125,548,685,","132,256,558,"
82,82,2019,Us,"256,091,919,","175,084,580,","81,007,339,"
83,83,2018,Halloween,"255,416,089,","159,366,015,","96,050,074,"
84,84,2017,Get Out,"252,297,405,","175,837,935,","76,459,470,"
85,85,2020,Dolittle,"251,410,631,","77,047,065,","174,363,566,"
86,86,2019,Glass,"246,999,039,","111,048,468,","135,950,571,"
87,87,2003,Love Actually,"246,671,987,","59,472,278,","187,199,709,"
88,88,1995,Babe,"246,100,000,","63,658,910,","182,441,090,"
89,89,2002,8 Mile,"245,768,384,","116,724,075,","129,044,309,"
90,90,2003,Hulk,"245,031,679,","132,177,234,","112,854,445,"
91,91,2022,The Bad Guys,"244,384,040,","96,393,095,","147,990,945,"
92,92,1990,Back to the Future Part III,"244,087,268,","88,055,283,","156,031,985,"
93,93,2012,American Reunion,"236,799,211,","56,758,835,","180,040,376,"
94,94,2003,2 Fast 2 Furious,"236,410,607,","127,120,058,","109,290,549,"
95,95,2007,Mr. Beanâ€™s Holiday,"234,981,342,","33,302,167,","201,679,175,"
96,96,1999,American Pie,"234,723,148,","101,800,948,","132,922,200,"
97,97,2003,American Wedding,"232,354,205,","104,354,205,","128,000,000,"
98,98,2009,Itâ€™s Complicated,"224,614,744,","112,735,375,","111,879,369,"
99,99,2014,Non-Stop,"222,383,055","91,742,160","130,640,895"